// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4iZ-Hn7LlFB0WETl4EtugfY2NUhYEbKw',
    appId: '1:263359359579:web:4d1fad259a85c32d216d7e',
    messagingSenderId: '263359359579',
    projectId: 'login-resiger-flutterapp',
    authDomain: 'login-resiger-flutterapp.firebaseapp.com',
    storageBucket: 'login-resiger-flutterapp.appspot.com',
    measurementId: 'G-WK4N8MLHD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXlMtaoVdWifaEI3ZwNxGlIVteXGb4J-s',
    appId: '1:263359359579:android:71c1ebb7e9c0417a216d7e',
    messagingSenderId: '263359359579',
    projectId: 'login-resiger-flutterapp',
    storageBucket: 'login-resiger-flutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbtzBArYRmnMT_wmZdREJeySY-0zWEVRY',
    appId: '1:263359359579:ios:0a8799a2a7b609f9216d7e',
    messagingSenderId: '263359359579',
    projectId: 'login-resiger-flutterapp',
    storageBucket: 'login-resiger-flutterapp.appspot.com',
    iosBundleId: 'com.example.enhansedLoginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbtzBArYRmnMT_wmZdREJeySY-0zWEVRY',
    appId: '1:263359359579:ios:0a8799a2a7b609f9216d7e',
    messagingSenderId: '263359359579',
    projectId: 'login-resiger-flutterapp',
    storageBucket: 'login-resiger-flutterapp.appspot.com',
    iosBundleId: 'com.example.enhansedLoginRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4iZ-Hn7LlFB0WETl4EtugfY2NUhYEbKw',
    appId: '1:263359359579:web:e35c6a609699fe3e216d7e',
    messagingSenderId: '263359359579',
    projectId: 'login-resiger-flutterapp',
    authDomain: 'login-resiger-flutterapp.firebaseapp.com',
    storageBucket: 'login-resiger-flutterapp.appspot.com',
    measurementId: 'G-V7D8MWQ4XX',
  );
}
